# Generated by Django 5.2.5 on 2025-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('accessed', models.DateTimeField(blank=True, null=True)),
                ('restricted', models.BooleanField(blank=True, null=True)),
                ('notifications', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField(blank=True, null=True)),
                ('langid', models.IntegerField(blank=True, null=True)),
                ('cli', models.CharField(blank=True, max_length=24, null=True)),
                ('ddi', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('keyzone', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('session', models.DateTimeField(blank=True, null=True)),
                ('sessid', models.IntegerField(blank=True, null=True)),
                ('packets', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=32, null=True)),
                ('contact', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('dedicated', models.BooleanField(blank=True, null=True)),
                ('billname', models.CharField(blank=True, max_length=64, null=True)),
                ('address1', models.CharField(blank=True, max_length=64, null=True)),
                ('address2', models.CharField(blank=True, max_length=64, null=True)),
                ('address3', models.CharField(blank=True, max_length=64, null=True)),
                ('address4', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'centres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('iso', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreid', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('contact', models.CharField(blank=True, max_length=64, null=True)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('oprid', models.IntegerField(blank=True, null=True)),
                ('cli', models.CharField(blank=True, max_length=32, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreid', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Missed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'missed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('centreid', models.IntegerField(blank=True, null=True)),
                ('langid', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=32, null=True)),
                ('fname', models.CharField(blank=True, max_length=32, null=True)),
                ('sname', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('calltotal', models.IntegerField(blank=True, null=True)),
                ('callduration', models.DurationField(blank=True, null=True)),
                ('accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreid', models.IntegerField(blank=True, null=True)),
                ('langid', models.IntegerField(blank=True, null=True)),
                ('acd', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operid', models.IntegerField(blank=True, null=True)),
                ('devid', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('callduration', models.DurationField(blank=True, null=True)),
                ('holdduration', models.DurationField(blank=True, null=True)),
                ('calltotal', models.IntegerField(blank=True, null=True)),
                ('missed', models.IntegerField(blank=True, null=True)),
                ('waiting', models.IntegerField(blank=True, null=True)),
                ('external', models.BooleanField(blank=True, null=True)),
                ('packets', models.IntegerField(blank=True, null=True)),
                ('media', models.CharField(blank=True, max_length=32, null=True)),
                ('silence', models.IntegerField(blank=True, null=True)),
                ('clearcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.IntegerField(blank=True, null=True)),
                ('tstamp', models.DateTimeField(blank=True, null=True)),
                ('ipadr', models.CharField(blank=True, max_length=32, null=True)),
                ('language', models.CharField(blank=True, max_length=32, null=True)),
                ('clienttime', models.CharField(blank=True, max_length=128, null=True)),
                ('application', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'signins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callid', models.IntegerField(blank=True, null=True)),
                ('silence', models.IntegerField(blank=True, null=True)),
                ('qualified', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suspects',
                'managed': False,
            },
        ),
    ]
